### ISSUE TITLE
Uninstall kfmon

### ISSUE THREAD

**Issue by leo-battin** [NiLuJe/kfmon#10]
So, there's an uninstaller package... Cool, what do we do with it? Instructions are unclear... I extracted it in the root of my ereader but nothing happened, I can still see the "kfmon successfully initialized" when booting it up.

**Comment by s1shed** [comment]
Inside of the zip file is a file named `KoboRoot.tgz`. Move this file to the `.kobo` directory and reboot your reader.

**Comment by NiLuJe** [comment]
Yup, works the exact same way as the install process (the OCP script also supports it).
