### ISSUE TITLE
Battery Issue

### ISSUE THREAD

**Issue by FrantzUml** [NiLuJe/kfmon#4]
Installing last vesrion of KFMon and Koreader (april 2019) makes battery issue : my Kobo Forma reader is quickly discharged (20% when cropping a simple pdf file !!).

**Comment by NiLuJe** [comment]
Not a KFMon issue ;).

Open a KOReader issue with *detailed* information. While being aware that the battery indicator on Kobos is lying approximately 95% of the time ;).
