### ISSUE TITLE
Private reporting of a potential security vulnerability

### ISSUE THREAD

**Issue by Sim4n6** [NiLuJe/kfmon#8]
Dear kfmon team,

I may have identified a security vulnerability in the codebase of the latest version of kfmon.
I would like to report it privately. Could you please consider to opt-in this Github [feature](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability).

Kind consideration
@Sim4n6

**Comment by NiLuJe** [comment]
Done.
